### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by wdsrocha** [BranislavBajuzik/ColorWallpaper#9]
Things I believe that could be helpful to anyone trying to use or contribute to this repository:
- Explain how to actually use the script, as I had to figure out on my own that the main file was `ColorWallpaper.py` so I could run `python src/ColorWallpaper.py` (this might not even be the correct way)
    * Suggested solution: Add the command you used to generate `example.png`
- Explain how to run and add new tests
    * Suggested solution: Add a contributing section

I really like how your code and repository are organized, this issue is just to address few things that I've struggled a bit when trying to use/contributing here.

**Comment by BranislavBajuzik** [comment]
Hi

- Yes, running the CollorWallpaper.py is the intended way
  - I made a release, I'll add a link to it to the readme
  - I like the example command, will definitely add that

- Will do, I just didn't expect anyone to want to contribute 😅

Thanks for the feedback 😊
